"""create_knowledge_rag_and_qualification_tables

Revision ID: 72effdf567d8
Revises: e3ae0be56290
Create Date: 2026-09-09 23:56:00.333818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72effdf567d8'
down_revision: Union[str, None] = 'e3ae0be56290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###