"""create_attribution_tables

Revision ID: dceb7953b476
Revises: 4b14249d32d5
Create Date: 2026-09-10 21:15:36.427229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dceb7953b476'
down_revision: Union[str, None] = '4b14249d32d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_attribution_rollups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('first_touch_credit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_touch_credit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('linear_credit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('attributed_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('metrics_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_attribution_rollups_campaign_id'), 'campaign_attribution_rollups', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_attribution_rollups_organization_id'), 'campaign_attribution_rollups', ['organization_id'], unique=False)
    op.create_table('attribution_touchpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('touchpoint_type', sa.String(length=32), nullable=False),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribution_touchpoints_lead_id'), 'attribution_touchpoints', ['lead_id'], unique=False)
    op.create_index(op.f('ix_attribution_touchpoints_occurred_at'), 'attribution_touchpoints', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attribution_touchpoints_occurred_at'), table_name='attribution_touchpoints')
    op.drop_index(op.f('ix_attribution_touchpoints_lead_id'), table_name='attribution_touchpoints')
    op.drop_table('attribution_touchpoints')
    op.drop_index(op.f('ix_campaign_attribution_rollups_organization_id'), table_name='campaign_attribution_rollups')
    op.drop_index(op.f('ix_campaign_attribution_rollups_campaign_id'), table_name='campaign_attribution_rollups')
    op.drop_table('campaign_attribution_rollups')
    # ### end Alembic commands ###